### ISSUE TITLE
Cannot change language setting

### ISSUE THREAD

**Issue by frederik-elwert** [LDAP/LSP-ltex-ls#10]
I am using the package for Markdown documents. It generally works fine, but I was not able to change the language of a document. Here’s what I tried:

* A `lang` setting in the YAML metadata block,
* A magic comment: `<!-- LTeX: language=de-DE -->`
* The server settings by adding `"ltex.language":"de-DE"`

The server still uses the default (`en-US`).

**Comment by LDAP** [comment]
Magic comment should work:
![grafik](https://user-images.githubusercontent.com/8215084/158649399-922f5218-c174-4b4a-9ab6-801bb11f21ac.png)
![grafik](https://user-images.githubusercontent.com/8215084/158649476-6a3da10b-aac2-412b-96e7-895bd2973025.png)

**Comment by frederik-elwert** [comment]
I don’t know why, but it does not seem to work for me:

![grafik](https://user-images.githubusercontent.com/3049661/158684968-1278b785-2dba-4562-a638-515872b4ebf4.png)

**Comment by LDAP** [comment]
Hi, thanks for the log. However, what you send was the console log. What I need is the language server log, which can be found in the panel as well:

Right-click on this icon: 
![image](https://user-images.githubusercontent.com/8215084/163453956-cd52b61f-4660-4721-a8c0-5cd59be98e02.png)
and select Output: Language Servers. The panel should now look like this after you open your `Test.md`:
![image](https://user-images.githubusercontent.com/8215084/163453847-0407a985-df5c-4e72-a0ee-781030f94ec0.png)

Please post the whole log between ltex-ls and sublime.

**Comment by frederik-elwert** [comment]
Oh, sorry!

I think now I found the culprit:

```
ltex-ls: Apr. 20, 2022 9:55:14 VORM. org.bsplines.ltexls.parsing.CodeFragmentizer$Companion create
ltex-ls: WARNUNG: Unsupported code language ID 'academicmarkdown', treating text as plaintext
ltex-ls: Apr. 20, 2022 9:55:14 VORM. org.bsplines.ltexls.server.DocumentChecker logTextToBeChecked
ltex-ls: FEIN: Checking the following text in language 'en-US' via LanguageTool: "<!-- LTeX: language=de-DE -->\n\nDies ist ein test der Spracheinstellung.\n"
ltex-ls: Apr. 20, 2022 9:55:17 VORM. org.bsplines.ltexls.server.DocumentChecker checkAnnotatedTextFragment
ltex-ls: FEIN: Obtained 6 rule matches

```

I am using the AcademicMarkdown package, and it appears that this causes LTeX to treat the document as plaintext instead of Markdown, making it fail to recognize the language settings. If I switch to Markdown from the MarkdownEditing package, it works as expected.

**Comment by LDAP** [comment]
The issue should be fixed when the next LSP plugin version is released. Feel free to reopen if the issue persists after updating.
