### ISSUE TITLE
ltex-ls exited with status code 1

### ISSUE THREAD

**Issue by poycc** [LDAP/LSP-ltex-ls#11]
when i open markdown file, sublime show message:
 ltex-ls exited with status code 1. Do you want to restart it? If you choose Cancel, it will be disabled for this window for the duration of the current session. Re-enable by running "LSP: Enable Language Server In Project" from the Command Palette.

m1, 12.4, java 18.0.1.1 2022-04-22

**Comment by LDAP** [comment]
This issue may be related to m1. Can you please send the output of the "troubleshoot server" command? You may need to activate the command then reactive the server if it was previously disabled because of the error.

**Comment by poycc** [comment]
# Troubleshooting: ltex-ls
## Version
 - LSP: 1.16.2
 - Sublime Text: 4126
## Server Test Run
 - exit code: 1
 - output
```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```
## Server Configuration
 - command
```json
[
  "${serverdir}/bin/${script}"
]
```
 - shell command
```sh
"/Users/123/Library/Caches/Sublime Text/Package Storage/LSP-ltex-ls/ltex-ls-15.2.0/bin/ltex-ls"
```
 - selector
```
text.tex, text.bibtex, text.html.markdown, text.restructuredtext
```
 - priority_selector
```
text.tex, text.bibtex, text.html.markdown, text.restructuredtext
```
 - init_options
```json
{}
```
 - settings
```json
{
  "ltex": {
    "additionalRules": {
      "languageModel": "", 
      "motherTongue": "", 
      "neuralNetworkModel": "", 
      "word2VecModel": ""
    }, 
    "checkFrequency": "edit", 
    "clearDiagnosticsWhenClosingFile": true, 
    "completionEnabled": false, 
    "configurationTarget": {
      "dictionary": "user", 
      "disabledRules": "user", 
      "hiddenFalsePositives": "user"
    }, 
    "diagnosticSeverity": "information", 
    "dictionary": {}, 
    "disabledRules": {}, 
    "enabled": [
      "bibtex", 
      "context", 
      "context.tex", 
      "html", 
      "latex", 
      "markdown", 
      "org", 
      "restructuredtext", 
      "rsweave"
    ], 
    "enabledRules": {}, 
    "hiddenFalsePositives": {}, 
    "java": {
      "path": ""
    }, 
    "language": "en-US", 
    "languageToolHttpServerUri": "", 
    "languageToolOrg": {
      "username": ""
    }, 
    "latex": {
      "commands": [], 
      "environments": []
    }, 
    "ltex-ls": {
      "languageToolOrgApiKey": "", 
      "logLevel": "fine"
    }, 
    "markdown": {
      "dummy": [], 
      "ignore": [], 
      "nodes": []
    }, 
    "sentenceCacheSize": 2000, 
    "trace": {
      "server": "off"
    }
  }
}
```
 - env
```json
{
  "JAVA_OPTS": "-Xms64m -Xmx512m"
}
```

## Active view
 - File name
```
/Users/zhudi/Documents/project/book-keeping/README.md
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Markdown/Markdown.sublime-syntax"
}
```
 - base scope
```
text.html.markdown
```

## Project / Workspace
 - folders
```json
[
  "/Users/123/Documents/project/book-keeping"
]
```
 - is project: False

## LSP configuration

<not found>
## System PATH
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /Users/13/.cargo/bin

**Comment by LDAP** [comment]
It seems that Java is not installed. 

You can check this by running 'java - version' in a terminal.

As far as I know, a native build is not available yet, but it should run fine with Rosetta. You can download Java here: https://www.java.com/de/ alternatively there should be also a brew recipe called openjdk.

I recommend to install version 17.

**Comment by poycc** [comment]
now i am successful of m1 by java 18.0.1.1 2022-04-22, first time i am used Arm 64 Compressed Archive, then set env path, but failed.last use Arm 64 DMG Installer and success, thanks.
