### ISSUE TITLE
allow installing a platform-dependent `ltex-ls` release (with java included)

### ISSUE THREAD

**Issue by junk1tm** [LDAP/LSP-ltex-ls#12]
Hi there, appreciate your work

Currently, `LSP-ltex-ls` always downloads the platform-independent release of `ltex-ls`, which requires the `java` runtime installed. I personally and many other users prefer to avoid such system-wide installations, so it would be nice to have an option to choose the type of `ltex-ls` release, with or without `java` bundled. Maybe the plugin should check if `JAVA_HOME` is set and if not, fallback to the platform-dependent version defined with `platform.system()`?

I could work on a PR, if you're interested

**Comment by LDAP** [comment]
Hi Tom,

If you are willing to provide a PR, I would be happy to merge it.

I like your suggestion to first check `JAVA_HOME` and only fall back to a platform dependent version if needed. Also, because I am not sure if there is even a version for ARM-based machines (e.g. M1/2 macs).

**Comment by junk1tm** [comment]
I've replaced the current installation with the `ltex-ls-15.2.0-mac-x64.tar.gz` release on my M1 machine and it works just fine! It contains `openjdk 11.0.12`, which is a x86-64 executable, so I guess it runs using Rosetta on Apple silicon.

I'll let you know when the PR is ready 🤝
